name: My first CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world action step
        run: echo "Hello world!"

      - name: Variables d'environnement
        run: |
          echo "Utilisateur Github : $GITHUB_ACTOR"
          echo "Nom du dépôt : $GITHUB_REPOSITORY"

      - name: Vérif de base sur Linux
        run: |
          uname -a
          ls -la
